name: Release
on:
  workflow_run:
    workflows: ['Tests']
    branches: [main, develop, beta, alpha, next]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Set Branch Environment Variable
        run: echo "export MY_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --branch $MY_BRANCH