name: Test and Release

on:
  push:
    branches: [main, develop, beta, alpha, next]
  pull_request:
    branches: [main, develop, beta, alpha, next]
    types: [closed]

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm ci
      - name: Give fixup script execute permissions
        run: chmod +x ./scripts/fixup_package_type.sh
      - name: Run Tests
        run: npm test
      - name: Echo NPM_TOKEN
        run: echo ${{ secrets.NPM_TOKEN }}
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
