name: Test on pull request

on:
  push:
    branches: ['feat/*']
  pull_request:
    branches: ['*']

jobs:
  test:
    name: Test on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
